services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
